# Generated by Django 2.2 on 2020-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='estimation',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
