# Generated by Django 2.2 on 2020-12-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201130_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='deadline',
        ),
    ]
